name: ImageAnalysis
dependencies:
  # Note: python 3.10 lead to inability to install py3exiv2.  Hence, fell back to python 3.8.10.
  - python=3.8.10
  - pip=22.1.2
  - pip:
    - opencv-python==4.6.0.66
    - opencv-utils==0.0.2
    - opencv-contrib-python==4.6.0.66
    - git+https://github.com/NavPy/NavPy.git
    - piexif==1.1.3
    - geojson==2.5.0
    - panda3d==1.10.11
    - pylint==2.14.5
    - pygraphviz==1.9
    - rope==1.3.0
    - matplotlib==3.5.2
    - tqdm==4.64.0
    - scipy==1.9.0
    - git+https://github.com/RiceCreekUAS/props-legacy.git/#subdirectory=python
    - py3exiv2==0.11.0
